name: template
description: This is my personal OS image.

base-image: quay.io/repository/fedora-ostree-desktops/silverblue
image-version: 41

modules:
  - type: rpm-ostree
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

